---
# mcMMO database file

# The type of database to use.
# Supported types: json, yaml
type: YAML

# Configuration for YAML
YAML:
  datafolder: profiles

# Configuration for JSON
JSON:
  datafolder: profiles
...
